server:
  port: 8080
feign:
  sentinel:
    enabled: true
#开启端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: spring-cloud-server-gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 表明gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务。
          enabled: true
          # 是将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了），比如以/service-hi/*的请求路径被路由转发到服务名为service-hi的服务上。
          lowerCaseServiceId: true
          filters:
            - StripPrefix=1
      routes:
        - id: spring-cloud-server-oauth
          uri: lb://spring-cloud-server-oauth
          predicates:
            - Path=/oauth/**
        - id: spring-cloud-service-user
          uri: lb://spring-cloud-service-user
          predicates:
            - Path=/user/**
        - id: testblog
          uri: https://blog.csdn.net/zhangchangbin123
          predicates:
          - Path=/blog/**
micro:
  framework:
    gateway:
      nacos:
        address: console.nacos.io:80
        data-id: spring-cloud-server-gateway
        group: DEFAULT_GROUP
        timeout: 5000
